### ISSUE TITLE
Add notification

### ISSUE THREAD

**Issue by not-a-feature** [not-a-feature/impfWidget#1]
Send a notification when appointments are available.
Possible implementation: from @wbrowar 's vaccine checker

```js
if (body) {
  const notify = new Notification();
  notify.sound = "default";
  notify.title = "COVID Vaccine Checker";
  notify.body = body;
  notify.openURL = "https://am-i-eligible.covid19vaccine.health.ny.gov";
  notify.schedule();
};
```
https://wbrowar.com/article/code/our-own-personal-vaccine-checker/

**Comment by Kolbi** [comment]
Bist du hier schon weiter?


Ist es eigentlich korrekt, dass er die Terminverfügbarkeit nur über https://003-iz.impfterminservice.de abruft? Die Zahl ist nur für den Loadbalancer gedacht? Oder gibt es mit 003, 004 oder 005 andere Ergebnisse, sprich die ID ist relevant für das Impfzentrum?

**Comment by not-a-feature** [comment]
Nope, wird aber die Tage gemacht.

Korrekt die Subdomain dient als Loadbalancer. 
Da jedoch am 24.02 zusätzlich ein Cookie-Basierter Loadbalancer dazu geschalten wurde (da Phase 2 in Hessen begonnen hat) muss das Konzept eh überdacht werden.
