### ISSUE TITLE
429 Too Many Request Error 

### ISSUE THREAD

**Issue by not-a-feature** [not-a-feature/impfWidget#6]
Today (09.03.2021) at 17:30 they introduced a new load balancer which is resulting in a non-functional Widget.

### header
```php
HTTP/1.1 429 Too Many Requests
Mime-Version: 1.0
Content-Length: 2
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
Content-Type: application/json
Expires: Tue, 09 Mar 2021 20:24:56 GMT
Cache-Control: max-age=0, no-cache, no-store
Pragma: no-cache
Date: Tue, 09 Mar 2021 20:24:56 GMT
Connection: keep-alive
Set-Cookie: _abck=...
```
### body
```
{}
```

**Comment by not-a-feature** [comment]
Wontfix due to EOL of project

**Comment by freedusa** [comment]
Makes me sad, still an actual issue to get vaccine appointments. I would greatly appreciate if there would be a solution :(
Somehow i could manage it to send the cookies via curl from my last visit, but didn't have the time to look further

**Comment by Lu-Kali** [comment]
> Makes me sad, still an actual issue to get vaccine appointments. I would greatly appreciate if there would be a solution :(
> Somehow i could manage it to send the cookies via curl from my last visit, but didn't have the time to look further

Did you already find a workaround to get it working?
