### ISSUE TITLE
Error?

### ISSUE THREAD

**Issue by MrUnknownDE** [not-a-feature/impfWidget#7]
Hallo,
Obwohl ich alles so gemacht habe wie es bei der Anleitung steht, kommt in mein Impfzentrum sowie in Berlin Error. 

https://user-images.githubusercontent.com/36811581/113010510-2e5f4d00-9179-11eb-9bf1-1ddc52f267c8.MP4

Mit freundlichen Grüßen 
Johannes

**Comment by not-a-feature** [comment]
Hi,

aufgrund einer Änderung des LoadBalancers vor einigen Wochne funktioniert das Widget nicht mehr.
Siehe https://github.com/not-a-feature/impfWidget/issues/6

End of Life des Projektes war am 09.03.2021
